version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./src:/var/www/html:cached
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./src:/var/www/html:cached
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    env_file:
      - env/phpfpm.env
      - env/psql_db.env
      - src/.env

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - './infra/redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]


  #  db:
#    image: mariadb:10.4
#    command:
#      --max_allowed_packet=64M
#      --optimizer_use_condition_selectivity=1
#      --optimizer_switch="rowid_filter=off"
#    ports:
#      - "3306:3306"
#    env_file: env/mysql_db.env
#    volumes:
#      - ./infra/mysql/mysql_dbdata:/var/lib/mysql:cached
#      - ./infra/mysql/my.cnf:/etc/mysql/my.cnf:cached
#      - db-store:/var/lib/mysql_dbdata

  db:
    image: postgres:13.3
    env_file: env/psql_db.env
    ports:
      - "5432:5432"

  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"

volumes:
  db-store:
  sockdata:
  appdata:
  ssldata: